### ISSUE TITLE
Broken on nightly as of 2018-06-10

### ISSUE THREAD

**Issue by ms-ati** [utkarshkukreti/speculate.rs#6]
```
error[E0624]: method `parse_block` is private
  --> /Users/msiegel/.cargo/registry/src/github.com-1ecc6299db9ec823/speculate-0.0.26/src/parser.rs:38:40
   |
38 |                     let block = parser.parse_block().unwrap();
   |                                        ^^^^^^^^^^^

error[E0624]: method `parse_ident` is private
  --> /Users/msiegel/.cargo/registry/src/github.com-1ecc6299db9ec823/speculate-0.0.26/src/parser.rs:51:40
   |
51 |                     let ident = parser.parse_ident().unwrap();
   |                                        ^^^^^^^^^^^

error[E0624]: method `parse_block` is private
  --> /Users/msiegel/.cargo/registry/src/github.com-1ecc6299db9ec823/speculate-0.0.26/src/parser.rs:53:40
   |
53 |                     let block = parser.parse_block().unwrap();
   |                                        ^^^^^^^^^^^

error[E0624]: method `parse_block` is private
  --> /Users/msiegel/.cargo/registry/src/github.com-1ecc6299db9ec823/speculate-0.0.26/src/parser.rs:65:40
   |
65 |                     before.push(parser.parse_block().unwrap());
   |                                        ^^^^^^^^^^^

error[E0624]: method `parse_block` is private
  --> /Users/msiegel/.cargo/registry/src/github.com-1ecc6299db9ec823/speculate-0.0.26/src/parser.rs:71:39
   |
71 |                     after.push(parser.parse_block().unwrap());
   |                                       ^^^^^^^^^^^

error[E0624]: method `span_fatal` is private
  --> /Users/msiegel/.cargo/registry/src/github.com-1ecc6299db9ec823/speculate-0.0.26/src/parser.rs:85:47
   |
85 |                         panic!("{:?}", parser.span_fatal(span, &message))
   |                                               ^^^^^^^^^^

error[E0624]: method `span_fatal` is private
  --> /Users/msiegel/.cargo/registry/src/github.com-1ecc6299db9ec823/speculate-0.0.26/src/parser.rs:94:35
   |
94 |             panic!("{:?}", parser.span_fatal(span, &message))
   |                                   ^^^^^^^^^^

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0624`.
error: Could not compile `speculate`.
```

And here's the version of rust:

```
$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.28.0-nightly (a805a2a5e 2018-06-10)
```

**Comment by ms-ati** [comment]
**WORKAROUND**: Until fixed for latest nightly, it works to pin to nightly from `2018-06-05` as follows:

```bash
rustup install nightly-2018-06-05
rustup default nightly-2018-06-05
```

**Comment by utkarshkukreti** [comment]
Looks like this will be fixed in the next nightly: https://github.com/rust-lang/rust/pull/51508.

**Comment by utkarshkukreti** [comment]
This works with `rustc 1.28.0-nightly (86a8f1a63 2018-06-17)` for me. Please let me know if you're still having problems!
